# Generated by Django 5.0.6 on 2024-06-22 10:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 44, 104969))),
                ('tag', models.CharField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete'), ('TRAIN', 'train')], max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student'), ('EXPERT', 'expert')], default='STUDENT', max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('expire', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'active_sessions',
            },
        ),
    ]
