# Generated by Django 3.2.5 on 2024-06-04 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 4, 15, 0, 45, 939771))),
                ('tag', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(default='admin', max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('expire', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'active_sessions',
            },
        ),
    ]
