# Generated by Django 3.2.5 on 2024-05-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_identials',
            },
        ),
        migrations.AddField(
            model_name='activesession',
            name='permision',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_authentication.useridential'),
        ),
    ]
