# Generated by Django 3.2.5 on 2024-06-04 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 15, 41, 10, 134315)),
        ),
    ]
