# Generated by Django 3.2.5 on 2024-05-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_remove_user_deparment'),
        ('api_authentication', '0002_auto_20240526_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user'),
        ),
        migrations.DeleteModel(
            name='UserIdential',
        ),
    ]
