# Generated by Django 3.2.5 on 2024-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0003_auto_20240526_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='permision',
        ),
        migrations.AddField(
            model_name='activesession',
            name='permission',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
