# Generated by Django 3.2.5 on 2024-05-27 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0004_auto_20240526_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 5, 27, 9, 51, 50, 77638))),
                ('tag', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
