# Generated by Django 3.2.5 on 2024-05-27 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 9, 58, 4, 367576)),
        ),
    ]
