# Generated by Django 5.0.6 on 2024-06-23 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0012_alter_log_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 13, 25, 619673)),
        ),
    ]
