# Generated by Django 5.0.6 on 2024-05-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("tag", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "logs",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("gender", models.BooleanField()),
                ("isAdmin", models.BooleanField()),
                ("isStudent", models.BooleanField()),
                ("isOfficer", models.BooleanField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                (
                    "deparment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_user.department",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
