# Generated by Django 5.0.6 on 2024-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('OFFICER', 'Officer')], default='student', max_length=100),
        ),
    ]
