# Generated by Django 5.0.6 on 2024-05-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deparment",
            field=models.ForeignKey(
                auto_created=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api_user.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.BooleanField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="isAdmin",
            field=models.BooleanField(auto_created=0),
        ),
    ]
