# Generated by Django 5.0.6 on 2024-06-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_user_gender_alter_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.department'),
        ),
    ]
