# Generated by Django 3.2.5 on 2024-05-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='isOfficer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
