# Generated by Django 3.2.5 on 2024-05-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_auto_20240526_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deparment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_user.department'),
        ),
    ]
