# Generated by Django 5.0.6 on 2024-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('officer', 'Officer')], default='student', max_length=100),
        ),
    ]
