# Generated by Django 3.2.5 on 2024-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_alter_user_deparment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deparment',
        ),
    ]
