# Generated by Django 3.2.5 on 2024-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_remove_user_deparment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isOfficer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isStudent',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
