# Generated by Django 3.2.5 on 2024-05-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_auto_20240526_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
