# Generated by Django 3.2.5 on 2024-05-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.BooleanField()),
                ('isAdmin', models.BooleanField()),
                ('isStudent', models.BooleanField()),
                ('isOfficer', models.BooleanField()),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.department')),
            ],
        ),
    ]
