# Generated by Django 3.2.5 on 2024-05-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
