# Generated by Django 3.2.5 on 2024-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('tag', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
