# Generated by Django 3.2.5 on 2024-05-24 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_model_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 24, 14, 12, 42, 833389)),
        ),
    ]
