# Generated by Django 5.0.6 on 2024-06-22 10:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('class_num', models.IntegerField()),
                ('train', models.FloatField()),
                ('test', models.FloatField()),
                ('val', models.FloatField()),
                ('classes', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.TextField(max_length=500)),
                ('concept', models.TextField(max_length=2000, null=True)),
                ('reason', models.TextField(max_length=2000, null=True)),
                ('symptom', models.TextField(max_length=2000, null=True)),
                ('consequence', models.TextField(max_length=2000, null=True)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('accuracy', models.FloatField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 27, 958668))),
                ('isActive', models.BooleanField(default=False)),
                ('dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_model.dataset')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.user')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('INFORMATION', 'information'), ('WARMING', 'warming')], default='INFORMATION', max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('isAnwserd', models.BooleanField(default=False)),
                ('tag', models.CharField(default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
                ('disease', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_model.disease')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.question')),
            ],
            options={
                'db_table': 'anwsers',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 27, 958668))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 27, 958668))),
                ('favorite', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), ('NORMAL', 'normal')], default='NORMAL', max_length=200)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.request')),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.CreateModel(
            name='ResponseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('disease', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_model.disease')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.response')),
            ],
            options={
                'db_table': 'responseDetails',
            },
        ),
    ]
