# Generated by Django 3.2.5 on 2024-06-04 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('class_num', models.IntegerField()),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.CreateModel(
            name='ResponseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.disease')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.response')),
            ],
            options={
                'db_table': 'responseDetails',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 4, 15, 1, 16, 875405))),
                ('isActive', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_model.dataset')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'models',
            },
        ),
    ]
