# Generated by Django 3.2.5 on 2024-06-04 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 15, 41, 9, 717451)),
        ),
        migrations.AlterField(
            model_name='model',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
