# Generated by Django 5.0.6 on 2024-05-25 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_label", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="created",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 5, 26, 0, 24, 53, 443305)
            ),
        ),
    ]
