# Generated by Django 5.0.6 on 2024-06-22 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 52, 670097)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 52, 670097)),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 17, 43, 52, 670097)),
        ),
    ]
