# Generated by Django 5.0.6 on 2024-05-26 07:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_label", "0002_alter_model_created"),
        ("api_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "diseases",
            },
        ),
        migrations.AlterField(
            model_name="model",
            name="created",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 5, 26, 14, 19, 7, 537145)
            ),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_user.user"
                    ),
                ),
            ],
            options={
                "db_table": "requests",
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_label.request",
                    ),
                ),
            ],
            options={
                "db_table": "responses",
            },
        ),
        migrations.CreateModel(
            name="ResponseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("compare", models.CharField(max_length=255)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_label.disease",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_label.response",
                    ),
                ),
            ],
            options={
                "db_table": "responseDetails",
            },
        ),
    ]
