# Generated by Django 5.0.6 on 2024-05-26 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_label", "0004_alter_model_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="created",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 5, 26, 15, 52, 18, 857469)
            ),
        ),
    ]
