# Generated by Django 5.0.6 on 2024-06-23 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0011_alter_model_created_alter_request_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 6, 42, 795878)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 6, 42, 795878)),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 6, 42, 796875)),
        ),
    ]
