# Generated by Django 5.0.6 on 2024-06-23 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0016_alter_model_created_alter_model_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 22, 58, 20, 979880)),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(choices=[('Da liễu', 'Da liễu'), ('Xương khớp', 'Xương khớp'), ('Não', 'Não')], default='Da liễu', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 22, 58, 20, 980876)),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 22, 58, 20, 981874)),
        ),
    ]
