# Generated by Django 5.0.6 on 2024-06-23 16:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0017_alter_model_created_alter_question_tag_and_more'),
        ('api_user', '0005_alter_department_description_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 23, 16, 16, 209371)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 23, 16, 16, 210368)),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 23, 16, 16, 210368)),
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.department')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_model.question')),
            ],
            options={
                'db_table': 'question_instance',
            },
        ),
    ]
