# Generated by Django 3.2.5 on 2024-05-26 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_label', '0020_alter_model_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 26, 23, 21, 4, 954125)),
        ),
        migrations.AlterField(
            model_name='model',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_label.dataset'),
        ),
    ]
