# Generated by Django 3.2.5 on 2024-05-26 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_auto_20240526_2211'),
        ('api_label', '0021_auto_20240526_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 23, 25, 59, 343254)),
        ),
        migrations.AlterField(
            model_name='model',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_user.user'),
        ),
    ]
