# Generated by Django 3.2.5 on 2024-05-26 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_label', '0022_auto_20240526_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 23, 29, 8, 159484)),
        ),
    ]
