# Generated by Django 3.2.5 on 2024-05-26 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_label', '0023_auto_20240526_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_label.dataset'),
        ),
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 0, 36, 36, 288441)),
        ),
    ]
