# Generated by Django 3.2.5 on 2024-05-26 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_label', '0024_auto_20240527_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 0, 41, 10, 135879)),
        ),
    ]
