# Generated by Django 3.2.5 on 2024-05-27 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_label', '0025_alter_model_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 8, 10, 10, 319054)),
        ),
    ]
