# Generated by Django 3.2.5 on 2024-05-27 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_label', '0026_auto_20240527_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 9, 20, 21, 236753)),
        ),
    ]
